// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVaultIndex(arg1) {
  return window['go']['vault']['Service']['GetVaultIndex'](arg1);
}

export function Invalidate() {
  return window['go']['vault']['Service']['Invalidate']();
}
