// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.AppConfig>;

export function SetConfig(arg1:config.AppConfig):Promise<config.AppConfig>;
