// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenExternal(arg1) {
  return window['go']['linkservice']['Service']['OpenExternal'](arg1);
}

export function SetContext(arg1) {
  return window['go']['linkservice']['Service']['SetContext'](arg1);
}
