// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {assetservice} from '../models';
import {context} from '../models';

export function ResolveAsset(arg1:string,arg2:string):Promise<assetservice.AssetRef>;

export function RevokeAsset(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;
