// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ResolveAsset(arg1, arg2) {
  return window['go']['assetservice']['Service']['ResolveAsset'](arg1, arg2);
}

export function RevokeAsset(arg1) {
  return window['go']['assetservice']['Service']['RevokeAsset'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['assetservice']['Service']['Shutdown'](arg1);
}

export function Start(arg1) {
  return window['go']['assetservice']['Service']['Start'](arg1);
}
