// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartWatch(arg1) {
  return window['go']['watcher']['Service']['StartWatch'](arg1);
}

export function StopWatch() {
  return window['go']['watcher']['Service']['StopWatch']();
}

export function WatchedPath() {
  return window['go']['watcher']['Service']['WatchedPath']();
}
