// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Changes():Promise<any>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UnwatchAllDocuments():Promise<void>;

export function UnwatchDocument(arg1:string):Promise<void>;

export function WatchDocument(arg1:string):Promise<void>;

export function WatchedPaths():Promise<Array<string>>;
