// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Changes() {
  return window['go']['watcher']['Service']['Changes']();
}

export function SetContext(arg1) {
  return window['go']['watcher']['Service']['SetContext'](arg1);
}

export function UnwatchAllDocuments() {
  return window['go']['watcher']['Service']['UnwatchAllDocuments']();
}

export function UnwatchDocument(arg1) {
  return window['go']['watcher']['Service']['UnwatchDocument'](arg1);
}

export function WatchDocument(arg1) {
  return window['go']['watcher']['Service']['WatchDocument'](arg1);
}

export function WatchedPaths() {
  return window['go']['watcher']['Service']['WatchedPaths']();
}
