// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Changes():Promise<any>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartWatch(arg1:string):Promise<void>;

export function StopWatch():Promise<void>;

export function WatchedPath():Promise<string>;
