// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppName() {
  return window['go']['main']['App']['AppName']();
}

export function EmitCommand(arg1) {
  return window['go']['main']['App']['EmitCommand'](arg1);
}

export function Print() {
  return window['go']['main']['App']['Print']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}
