// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fileservice} from '../models';

export function OpenDocument():Promise<fileservice.OpenDocumentResult>;

export function OpenDocumentAt(arg1:string):Promise<fileservice.OpenDocumentResult>;

export function ReadDocument(arg1:string):Promise<fileservice.DocumentBytes>;
