// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDocument() {
  return window['go']['fileservice']['Service']['OpenDocument']();
}

export function OpenDocumentAt(arg1) {
  return window['go']['fileservice']['Service']['OpenDocumentAt'](arg1);
}

export function ReadDocument(arg1) {
  return window['go']['fileservice']['Service']['ReadDocument'](arg1);
}

export function SetContext(arg1) {
  return window['go']['fileservice']['Service']['SetContext'](arg1);
}
